### ISSUE TITLE
Unable to view animation

### ISSUE THREAD

**Issue by dparkar** [yeyus/react-vertical-timeline#3]
I am seeing just the plain text in the browser. I have tried some other components as well and seen the same behavior. Probably I am missing something as I am just getting started with React. Here's a screen shot, would really appreciate the help : 
![image](https://user-images.githubusercontent.com/208161/30415717-281c83a0-98de-11e7-8a82-05adcc9a5ad7.png)

**Comment by yeyus** [comment]
My guess is that you're missing the import of the CSS

**Comment by dparkar** [comment]
Thank you. That was it.
