### ISSUE TITLE
Error when trying to implement

### ISSUE THREAD

**Issue by jskrt** [yeyus/react-vertical-timeline#4]
Running into this error when trying to use it in a GatsbyJS React project:

`Uncaught (in promise) TypeError: Cannot read property 'node' of undefined`

Any ideas?

Here's my code: https://paste.ofcode.org/yuhEHFuQ64esjFffD3aquR

**Comment by jskrt** [comment]
@yeyus I think the prop-types need to be updated

**Comment by yeyus** [comment]
@jskrt thanks for reporting. I will take a look.

**Comment by yeyus** [comment]
@jskrt I updated the boilerplate code and pushed `0.2.0` https://github.com/yeyus/react-vertical-timeline/pull/5 . This should fix the issue.

Feel free to reopen if you still have the issue.
